### ISSUE TITLE
Deep Medic Segmentation Crashing

### ISSUE THREAD

**Issue by dboun** [CBICA/CaPTk#668]
**Describe the bug**
Exits with error != 0

**To Reproduce**
```DeepMedic -t1 ./T1.nii.gz -t1c ./T1CE.nii.gz -t2 ./T2.nii.gz -fl ./FLAIR.nii.gz -o ./out -md /home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepMedic/saved_models/brainTumorSegmentation -d 1```

**CaPTk Version**
1.7.2

**Desktop (please complete the following information):**
Linux Mint 19.2

**Additional context**
```
DeepMedic -t1 ./T1.nii.gz -t1c ./T1CE.nii.gz -t2 ./T2.nii.gz -fl ./FLAIR.nii.gz -o ./out -md /home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepMedic/saved_models/brainTumorSegmentation -d 1
=== Checking and rectifying (z-score) normalization status.
== Starting Normalization of T1CE image.
Cut-offs calculated: Lower = -29.1722; Upper = 987.795
== Done.
== Starting Normalization of T1 image.
Cut-offs calculated: Lower = 100.901; Upper = 681.911
== Done.
== Starting Normalization of T2 image.
Cut-offs calculated: Lower = -53.0126; Upper = 324.043
== Done.
== Starting Normalization of T2-Flair image.
Cut-offs calculated: Lower = -27.9178; Upper = 466.2
== Done.
=== Done.
=== Starting resampling of images to isotropic resolution.
=== Done.
Starting DeepMedic Segmentation.
Given configuration file:  /home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepMedic/saved_models/brainTumorSegmentation/modelConfig.txt
Given configuration file:  /home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepmedic/configFiles/testApiConfig.txt
Traceback (most recent call last):
  File "deepMedic_test_cmdLnApi.py", line 198, in <module>
  File "deepmedic/frontEnd/configParsing/testConfig.py", line 50, in __init__
  File "deepmedic/frontEnd/configParsing/config.py", line 17, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepmedic/configFiles/testApiConfig.txt'
[4419] Failed to execute script deepMedic_test_cmdLnApi
DeepMedic exited with code !=0.
```

**Comment by dboun** [comment]
Also in --help it says '-m' where it should say '-md'

**Comment by sarthakpati** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepmedic/configFiles/testApiConfig.txt'

This error is correct. The location should be: ```/home/dimitris/CaPTk/1.7.2/squashfs-root/usr/data/deepMedic/configFiles/testApiConfig.txt```
